export const categoryFieldMap: Record<string, Record<string, string>> = {
  // 1. Gadjetlar
  "1": {
    "1.1.1": "name",
    "1.1.2": "turi",
    "1.1.3": "ishlab_chiqarilgan_davlat",
    "1.1.4": "ishlab_chiqaruvchi_tashkilot",
    "1.1.5": "kafolat_muddati",
    "1.1.6": "ishlash_muddati",
    "1.2.1": "olchami",
    "1.2.2": "ogirligi",
    "1.2.3": "batareya_sigimi",
    "1.2.4": "quvvati",
    "1.2.5": "energiya_sarfi",
    "1.2.6": "ekran_olchami",
    "1.2.7": "protsessor_turi",
    "1.2.8": "operativ_xotira",
    "1.2.9": "doimiy_xotira",
    "1.2.10": "operatsion_tizim",
    "1.2.11": "kamera_korsatkichlari",
    "1.2.12": "yangi_texnologiyalar",
    "1.3.1": "materiallar",
    "1.3.2": "qadoqlash_materiali",
    "1.3.3": "qayta_ishlash_imkoniyati",
    "1.4.1": "sertifikatlari",
    "1.4.2": "maxsus_xavfsizlik_sertifikati",
    "1.4.3": "saqlash_yoriqnoma",
    "1.4.4": "tamirlash_imkoniyati",
  },

  // 2. Maishiy texnika
  "2": {
    "2.1.1": "name",
    "2.1.2": "modeli",
    "2.1.3": "olchami",
    "2.1.4": "ogirligi",
    "2.1.5": "ishlab_chiqarilgan_davlat",
    "2.1.6": "ishlab_chiqaruvchi_tashkilot",
    "2.1.7": "kafolat_muddati",
    "2.1.8": "ishlash_muddati",
    "2.2.1": "quvvati",
    "2.2.2": "elektr_taminoti",
    "2.2.3": "energiya_samaradorligi",
    "2.2.4": "energiya_sarfi",
    "2.2.5": "suv_sarfi",
    "2.2.6": "shovqin_darajasi",
    "2.2.7": "foydalanish_qulayligi",
    "2.2.8": "maxsus_xavfsizlik_funktsiyalari",
    "2.3.1": "material",
    "2.3.2": "qadoqlash_turi",
    "2.3.3": "qayta_ishlash_imkoniyati",
    "2.4.1": "zaxira_qismlar",
    "2.4.2": "tamirlash_yoriqnoma",
    "2.4.3": "saqlash_sharoiti",
    "2.4.4": "sertifikatlar",
  },

  // 3. Kiyim
  "3": {
    "3.1.1": "name",
    "3.1.2": "kiyim_turi",
    "3.1.3": "olchami",
    "3.1.4": "ogirligi",
    "3.1.5": "rangi",
    "3.1.6": "ishlab_chiqarilgan_davlat",
    "3.1.7": "ishlab_chiqaruvchi_tashkilot",
    "3.1.8": "ishlab_chiqarilgan_sana",
    "3.1.9": "dizayner_brand",
    "3.1.10": "moda_malumoti",
    "3.2.1": "asosiy_material",
    "3.2.2": "material_foizi",
    "3.2.3": "maxsus_ishlov",
    "3.2.4": "sertifikat",
    "3.2.5": "ekologik_belgi",
    "3.3.1": "yuvish_yoriqnoma",
    "3.3.2": "dazmollash_yoriqnoma",
    "3.3.3": "qadoqlash_materiali",
    "3.3.4": "saqlash_muddati",
    "3.3.5": "xizmat_muddati",
    "3.4.1": "qayta_ishlash_imkoniyati",
  },

    // 4. Oziq-ovqat (Food)
  "4": {
    "4.1.1": "name",
    "4.1.2": "mahsulot_turi",
    "4.1.3": "ogirligi",
    "4.1.4": "ishlab_chiqarilgan_sana",
    "4.1.5": "yaroqlilik_muddati",
    "4.1.6": "saqlash_muddati",
    "4.1.7": "narx_segmenti",
    "4.1.8":"yetkazib_beruvchi_nomi",
    "4.1.9":"ishlab_chiqaruvchi_nomi",
    "4.1.10":"ishlab_chiqarilgan_davlat",
    "4.2.1": "tarkibi",
    "4.2.2": "energiya_qiymati",
    "4.2.3": "allergiya_ogohlantirish",
    "4.2.4": "maxsus_tamga",
    "4.2.5": "ekologik_iz",
    "4.3.1": "saqlash_sharoiti",
    "4.3.2": "qadoqlash_materiali",
    "4.3.3": "qayta_ishlash_mumkinmi",
    "4.4.1": "sertifikatlar",
  },
  // 5. Qurilish
  "5": {
    "5.1.1": "name",
    "5.1.2": "olchami",
    "5.1.3": "ogirligi",
    "5.1.4": "ishlab_chiqaruvchi_tashkilot",
    "5.1.5": "ishlab_chiqarilgan_davlat",
    "5.1.6": "saqlash_sharoiti",
    "5.2.1": "tarkibiy_materiallar",
    "5.2.2": "mustahkamlik_korsatkichi",
    "5.2.3": "suvga_chidamlilik",
    "5.2.4": "issiqqa_chidamlilik",
    "5.2.5": "yonuvchanlik",
    "5.2.6": "foydalanish_sohasi",
    "5.2.7": "tamirlash_moslik",
    "5.3.1": "saqlash_sharoiti",
    "5.3.2": "qadoqlash_turi",
    "5.3.3": "qayta_ishlash_imkoniyati",
    "5.3.4": "ekologik_xavfsizlik",
    "5.4.1": "sertifikatlar",
  },

  // 6. Aksessuarlar
  "6": {
    "6.1.1": "name",
    "6.1.2": "modeli",
    "6.1.3": "olchami",
    "6.1.4": "ogirligi",
    "6.1.5": "rangi",
    "6.1.6": "ishlab_chiqaruvchi_tashkilot",
    "6.1.7": "ishlab_chiqarilgan_davlat",
    "6.1.8": "xizmat_muddati",
    "6.2.1": "material",
    "6.2.2": "dizayner",
    "6.2.3": "maxsus_belgilar",
    "6.3.1": "qadoqlash_materiali",
    "6.3.2": "qayta_ishlash_imkoniyati",
    "6.3.3": "saqlash_yoriqnoma",
    "6.4.1": "sertifikatlar",
    "6.4.2": "tamirlash_imkoniyati",
  },

  // 7. Salomatlik
  "7": {
    "7.1.1": "name",
    "7.1.2": "mahsulot_turi",
    "7.1.3": "ogirligi",
    "7.1.4": "ishlab_chiqaruvchi_tashkilot",
    "7.1.5": "ishlab_chiqarilgan_davlat",
    "7.1.6": "saqlash_muddati",
    "7.1.7": "kafolat_muddati",
    "7.2.1": "material",
    "7.2.2": "saqlash_sharoiti",
    "7.2.3": "xavfsizlik_talablar",
    "7.2.4": "tibbiy_standartlar",
    "7.2.5": "foydalanish_sohasi",
    "7.3.1": "saqlash_sharoiti",
    "7.3.2": "qadoqlash_turi",
    "7.3.3": "qayta_ishlash_mumkinmi",
    "7.4.1": "sertifikat_turi",
  },

  // 8. Uy-ro‘zg‘or buyumlari (xomashyo emas)
  "8": {
    "8.1.1": "name",
    "8.1.2": "mahsulot_turi",
    "8.1.3": "olchami",
    "8.1.4": "ogirligi",
    "8.1.5": "rangi",
    "8.1.6": "ishlab_chiqaruvchi_tashkilot",
    "8.1.7": "ishlab_chiqarilgan_davlat",
    "8.1.8": "xizmat_muddati",
    "8.2.1": "material",
    "8.2.2": "mustahkamlik_darajasi",
    "8.3.1": "qadoqlash_materiali",
    "8.3.2": "qayta_ishlash_imkoniyati",
    "8.3.3": "saqlash_yoriqnoma",
    "8.4.1": "sertifikatlar",
    "8.4.2": "tamirlash_imkoniyati",
  },

  // 9. Xomashyo
  "9": {
    "9.1.1": "name",
    "9.1.2": "mahsulot_turi",
    "9.1.3": "olchami",
    "9.1.4": "ogirligi",
    "9.1.5": "rangi",
    "9.1.6": "ishlab_chiqaruvchi_tashkilot",
    "9.1.7": "ishlab_chiqarilgan_davlat",
    "9.1.8": "ishlash_muddati",
    "9.1.9": "narx_segmenti",
    "9.2.1": "material",
    "9.2.2": "sifat_darajasi",
    "9.3.1": "qadoqlash_turi",
    "9.3.2": "qayta_ishlash_mumkinmi",
    "9.3.3": "saqlash_sharoiti",
    "9.4.1": "sertifikatlar",
    "9.4.2": "ekologik_xavfsizlik",
  },
};

export const getReverseFieldMap = (categoryKey: string): Record<string, string> => {
  const map: Record<string, string> = {};
  const fieldMap = categoryFieldMap[categoryKey] || {};
  Object.entries(fieldMap).forEach(([uiId, apiField]) => {
    map[apiField] = uiId;
  });
  return map;
};

// const categoryFieldMap: Record<string, Record<string, string>> = {
//   // 1. Gadjetlar
//   "1": {
//     "1.1.1": "name",
//     "1.1.2": "turi",
//     "1.1.3": "ishlab_chiqarilgan_davlat",
//     "1.1.4": "ishlab_chiqaruvchi_tashkilot",
//     "1.1.5": "kafolat_muddati",
//     "1.1.6": "ishlash_muddati",
//     "1.2.1": "olchami",
//     "1.2.2": "ogirligi",
//     "1.2.3": "batareya_sigimi",
//     "1.2.4": "quvvati",
//     "1.2.5": "energiya_sarfi",
//     "1.2.6": "ekran_olchami",
//     "1.2.7": "protsessor_turi",
//     "1.2.8": "operativ_xotira",
//     "1.2.9": "doimiy_xotira",
//     "1.2.10": "operatsion_tizim",
//     "1.2.11": "kamera_korsatkichlari",
//     "1.2.12": "yangi_texnologiyalar",
//     "1.3.1": "materiallar",
//     "1.3.2": "qadoqlash_materiali",
//     "1.3.3": "qayta_ishlash_imkoniyati",
//     "1.4.1": "sertifikatlari",
//     "1.4.2": "maxsus_xavfsizlik_sertifikati",
//     "1.4.3": "saqlash_yoriqnoma",
//     "1.4.4": "tamirlash_imkoniyati",
//   },

//   // 2. Maishiy texnika
//   "2": {
//     "2.1.1": "name",
//     "2.1.2": "modeli",
//     "2.1.3": "olchami",
//     "2.1.4": "ogirligi",
//     "2.1.5": "ishlab_chiqarilgan_davlat",
//     "2.1.6": "ishlab_chiqaruvchi_tashkilot",
//     "2.1.7": "kafolat_muddati",
//     "2.1.8": "ishlash_muddati",
//     "2.2.1": "quvvati",
//     "2.2.2": "elektr_taminoti",
//     "2.2.3": "energiya_samaradorligi",
//     "2.2.4": "energiya_sarfi",
//     "2.2.5": "suv_sarfi",
//     "2.2.6": "shovqin_darajasi",
//     "2.2.7": "foydalanish_qulayligi",
//     "2.2.8": "maxsus_xavfsizlik_funktsiyalari",
//     "2.3.1": "material",
//     "2.3.2": "qadoqlash_turi",
//     "2.3.3": "qayta_ishlash_imkoniyati",
//     "2.4.1": "zaxira_qismlar",
//     "2.4.2": "tamirlash_yoriqnoma",
//     "2.4.3": "saqlash_sharoiti",
//     "2.4.4": "sertifikatlar",
//   },

//   // 3. Kiyim
//   "3": {
//     "3.1.1": "name",
//     "3.1.2": "kiyim_turi",
//     "3.1.3": "olchami",
//     "3.1.4": "ogirligi",
//     "3.1.5": "rangi",
//     "3.1.6": "ishlab_chiqarilgan_davlat",
//     "3.1.7": "ishlab_chiqaruvchi_tashkilot",
//     "3.1.8": "ishlab_chiqarilgan_sana",
//     "3.1.9": "dizayner_brand",
//     "3.1.10": "moda_malumoti",
//     "3.2.1": "asosiy_material",
//     "3.2.2": "material_foizi",
//     "3.2.3": "maxsus_ishlov",
//     "3.2.4": "sertifikat",
//     "3.2.5": "ekologik_belgi",
//     "3.3.1": "yuvish_yoriqnoma",
//     "3.3.2": "dazmollash_yoriqnoma",
//     "3.3.3": "qadoqlash_materiali",
//     "3.3.4": "saqlash_muddati",
//     "3.3.5": "xizmat_muddati",
//     "3.4.1": "qayta_ishlash_imkoniyati",
//   },

//     // 4. Oziq-ovqat (Food)
//   "4": {
//     "4.1.1": "name",
//     "4.1.2": "mahsulot_turi",
//     "4.1.3": "ogirligi",
//     "4.1.4": "ishlab_chiqarilgan_sana",
//     "4.1.5": "yaroqlilik_muddati",
//     "4.1.6": "saqlash_muddati",
//     "4.1.7": "narx_segmenti",
//     "4.1.8":"yetkazib_beruvchi_nomi",
//     "4.1.9":"ishlab_chiqaruvchi_nomi",
//     "4.1.10":"ishlab_chiqarilgan_davlat",
//     "4.2.1": "tarkibi",
//     "4.2.2": "energiya_qiymati",
//     "4.2.3": "allergiya_ogohlantirish",
//     "4.2.4": "maxsus_tamga",
//     "4.2.5": "ekologik_iz",
//     "4.3.1": "saqlash_sharoiti",
//     "4.3.2": "qadoqlash_materiali",
//     "4.3.3": "qayta_ishlash_mumkinmi",
//     "4.4.1": "sertifikatlar",
//   },
//   // 5. Qurilish
//   "5": {
//     "5.1.1": "name",
//     "5.1.2": "olchami",
//     "5.1.3": "ogirligi",
//     "5.1.4": "ishlab_chiqaruvchi_tashkilot",
//     "5.1.5": "ishlab_chiqarilgan_davlat",
//     "5.1.6": "saqlash_sharoiti",
//     "5.2.1": "tarkibiy_materiallar",
//     "5.2.2": "mustahkamlik_korsatkichi",
//     "5.2.3": "suvga_chidamlilik",
//     "5.2.4": "issiqqa_chidamlilik",
//     "5.2.5": "yonuvchanlik",
//     "5.2.6": "foydalanish_sohasi",
//     "5.2.7": "tamirlash_moslik",
//     "5.3.1": "saqlash_sharoiti",
//     "5.3.2": "qadoqlash_turi",
//     "5.3.3": "qayta_ishlash_imkoniyati",
//     "5.3.4": "ekologik_xavfsizlik",
//     "5.4.1": "sertifikatlar",
//   },

//   // 6. Aksessuarlar
//   "6": {
//     "6.1.1": "name",
//     "6.1.2": "modeli",
//     "6.1.3": "olchami",
//     "6.1.4": "ogirligi",
//     "6.1.5": "rangi",
//     "6.1.6": "ishlab_chiqaruvchi_tashkilot",
//     "6.1.7": "ishlab_chiqarilgan_davlat",
//     "6.1.8": "xizmat_muddati",
//     "6.2.1": "material",
//     "6.2.2": "dizayner",
//     "6.2.3": "maxsus_belgilar",
//     "6.3.1": "qadoqlash_materiali",
//     "6.3.2": "qayta_ishlash_imkoniyati",
//     "6.3.3": "saqlash_yoriqnoma",
//     "6.4.1": "sertifikatlar",
//     "6.4.2": "tamirlash_imkoniyati",
//   },

//   // 7. Salomatlik
//   "7": {
//     "7.1.1": "name",
//     "7.1.2": "mahsulot_turi",
//     "7.1.3": "ogirligi",
//     "7.1.4": "ishlab_chiqaruvchi_tashkilot",
//     "7.1.5": "ishlab_chiqarilgan_davlat",
//     "7.1.6": "saqlash_muddati",
//     "7.1.7": "kafolat_muddati",
//     "7.2.1": "material",
//     "7.2.2": "saqlash_sharoiti",
//     "7.2.3": "xavfsizlik_talablar",
//     "7.2.4": "tibbiy_standartlar",
//     "7.2.5": "foydalanish_sohasi",
//     "7.3.1": "saqlash_sharoiti",
//     "7.3.2": "qadoqlash_turi",
//     "7.3.3": "qayta_ishlash_mumkinmi",
//     "7.4.1": "sertifikat_turi",
//   },

//   // 8. Uy-ro‘zg‘or buyumlari (xomashyo emas)
//   "8": {
//     "8.1.1": "name",
//     "8.1.2": "mahsulot_turi",
//     "8.1.3": "olchami",
//     "8.1.4": "ogirligi",
//     "8.1.5": "rangi",
//     "8.1.6": "ishlab_chiqaruvchi_tashkilot",
//     "8.1.7": "ishlab_chiqarilgan_davlat",
//     "8.1.8": "xizmat_muddati",
//     "8.2.1": "material",
//     "8.2.2": "mustahkamlik_darajasi",
//     "8.3.1": "qadoqlash_materiali",
//     "8.3.2": "qayta_ishlash_imkoniyati",
//     "8.3.3": "saqlash_yoriqnoma",
//     "8.4.1": "sertifikatlar",
//     "8.4.2": "tamirlash_imkoniyati",
//   },

//   // 9. Xomashyo
//   "9": {
//     "9.1.1": "name",
//     "9.1.2": "mahsulot_turi",
//     "9.1.3": "olchami",
//     "9.1.4": "ogirligi",
//     "9.1.5": "rangi",
//     "9.1.6": "ishlab_chiqaruvchi_tashkilot",
//     "9.1.7": "ishlab_chiqarilgan_davlat",
//     "9.1.8": "ishlash_muddati",
//     "9.1.9": "narx_segmenti",
//     "9.2.1": "material",
//     "9.2.2": "sifat_darajasi",
//     "9.3.1": "qadoqlash_turi",
//     "9.3.2": "qayta_ishlash_mumkinmi",
//     "9.3.3": "saqlash_sharoiti",
//     "9.4.1": "sertifikatlar",
//     "9.4.2": "ekologik_xavfsizlik",
//   },
// };


